# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CETAC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CETAC
  # add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'Firebase/Auth'
pod 'Firebase/Core'

pod 'Charts'


end
